config/routes.rb
Rails.application.routes.draw do
  resources :days
  resources :weeks
  resources :schedules
  root to: 'visitors#index'
  devise_for :users
  resources :users
  get 'days/:id/mark_completed', to: "days#mark_completed", as: 'mark_completed'
end

app/models/schedule.rb
class Schedule < ActiveRecord::Base
  belongs_to :user
  has_many :weeks, dependent: :destroy

  validates :name, presence: true
  validates :race_day, presence: true

  attr_accessor :login
  
  def self.full_marathon_advanced
    training_weeks = 18
    {
      :short_run => [3, 3, 3, 3, 3, 3, 4, 4, 4, 4, 5, 5, 5, 5, 5, 5, 4, 3, 3],
      :medium_run => [5, 5, 6, 6, 7, 7, 8, 8, 9, 9, 10, 6, 10, 6, 10, 8, 6, 4, 3],
      :long_run => [10, 11, 8, 13, 14, 10, 16, 17, 13.1, 19, 20, 12, 20, 12, 20, 12, 8, 8],
      :rest => duplicate_string_array('rest', training_weeks + 1),
      :cross_train => duplicate_string_array('cross train', training_weeks + 1),
      :weeks => training_weeks
    }
  end

  def self.full_marathon
    training_weeks = 18
    {
      :short_run => [3, 3, 3, 3, 3, 3, 4, 4, 4, 4, 5, 5, 5, 5, 5, 5, 4, 3, 3],
      :medium_run => [5, 5, 5, 6, 6, 6, 7, 7, 7, 8, 8, 8, 5, 8, 5, 4, 3, 2, 2],
      :long_run => [5, 6, 7, 8, 10, 11, 12, 14, 16, 16, 17, 18, 19, 20, 22, 12, 8, 8],
      :rest => duplicate_string_array('rest', training_weeks + 1),
      :cross_train => duplicate_string_array('cross train', training_weeks + 1),
      :weeks => training_weeks
    }
  end

  def self.half_marathon
    training_weeks = 12
    {
      :short_run => duplicate_string_array('3', training_weeks + 1),
      :medium_run => [3, 3, 4, 4, 4, 4, 5, 5, 5, 5, 5, 2, 2],
      :long_run => [4, 5, 6, 7, 8, 3.1, 9, 10, 6.2, 11, 12, 6],
      :rest => duplicate_string_array('rest', training_weeks + 1),
      :cross_train => duplicate_string_array('cross train', training_weeks + 1),
      :weeks => training_weeks
    }
  end

  def self.ten_k
    training_weeks = 8
    {
      :short_run => [2.5, 2.5, 2.5, 3, 3, 3, 3, 3, 3], 
      :medium_run => [3, 3, 3, 4, 4, 4, 4, 4, 3],
      :long_run => [3, 3.5, 4, 4, 4.5, 5, 5.5, 5],
      :rest => duplicate_string_array('rest', training_weeks + 1),
      :cross_train => duplicate_string_array('cross train', training_weeks + 1),
      :weeks => training_weeks
    }
  end

  def self.five_k
    training_weeks = 8
    {
      :short_run => [1.5, 1.5, 1.5, 1.5, 2, 2, 2, 2, 2],
      :medium_run => [1.5, 1.75, 2, 2.25, 2.5, 2.75, 3, 3, 3],
      :long_run => [3, 3.5, 4, 4, 4.5, 5, 5.5, 5],
      :rest => duplicate_string_array('rest', training_weeks + 1),
      :cross_train => duplicate_string_array('cross train', training_weeks + 1),
      :weeks => training_weeks
    }
  end

  def update_weeks
    total_weeks = self.training_info[:weeks] + 1
    (1..total_weeks).each do |week_num|
      week = Week.where({
        :schedule_id => self.id,
        :number => week_num
      }).first_or_initialize
      week.save!
    end
  end

  def update_days
    training_day = self.start_date(self.training_info[:weeks])

    self.weeks.sort.each_with_index do |week, index|
      (1..7).each do |_x|

        if training_day == self.race_day
          activity = "Race Day"
        elsif training_day == self.race_day - 1 || training_day == self.race_day - 2
          activity = "rest"
        else
          activity_type = self.send(training_day.strftime('%A').downcase.to_sym).sub(" ","_").to_sym
          activity = self.training_info[activity_type][index]
        end

        day = Day.where({
          :week_id => week.id,
          :activity => activity,
          :date => training_day,
          :completed => false
        }).first_or_initialize
        day.save!

        return true if training_day == self.race_day
        training_day += 1
      end
    end
  end
  
  def training_info
    Schedule.send(self.race_type.tr(" ","_"))
  end

  def start_date(weeks)
    self.race_day - weeks * 7 - self.race_day.wday + 1
  end

  def self.duplicate_string_array(word, number)
    array = [] 
    number.times do |_x|
      array << word
    end
    array
  end
end

app/controllers/schedules_controller.rb
class SchedulesController < ApplicationController
  before_action :set_schedule, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!, only: [:new, :index, :edit, :show]

  # GET /schedules
  # GET /schedules.json
  def index
    @user = current_user
    @schedules = @user.schedules 
  end

  # GET /schedules/1
  # GET /schedules/1.json
  def show
    @schedule = Schedule.find(params[:id])
    if @schedule.user == current_user
      @schedule
    else
      render(:file => File.join(Rails.root, 'public/403.html'), :status => 403, :layout => false)
    end
  end

  # GET /schedules/new
  def new
    @schedule = current_user.schedules.new
  end

  # GET /schedules/1/edit
  def edit
  end

  # POST /schedules
  # POST /schedules.json
  def create
    @schedule = current_user.schedules.new(schedule_params)
    
    respond_to do |format|
      if @schedule.save
        @schedule.update_weeks
        @schedule.update_days
        format.html { redirect_to @schedule, notice: 'Schedule was successfully created.' }
        format.json { render :show, status: :created, location: @schedule }
      else
        format.html { render :new }
        format.json { render json: @schedule.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /schedules/1
  # PATCH/PUT /schedules/1.json
  def update
    respond_to do |format|
      if @schedule.update(schedule_params)
        format.html { redirect_to @schedule, notice: 'Schedule was successfully updated.' }
        format.json { render :show, status: :ok, location: @schedule }
      else
        format.html { render :edit }
        format.json { render json: @schedule.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /schedules/1
  # DELETE /schedules/1.json
  def destroy
    @schedule.destroy
    respond_to do |format|
      format.html { redirect_to schedules_url, notice: 'Schedule was successfully deleted.' }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_schedule
    @schedule = Schedule.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def schedule_params
    params.require(:schedule).permit(:race_day, :monday, :tuesday, :wednesday, :thursday, :friday, :saturday, :sunday, :race_type, :user_id, :name)
  end
end

app/helpers/schedules_helper.rb
module SchedulesHelper
end

app/views/schedules/_form.html.erb
<%= form_for(@schedule) do |f| %>
<div class="row">
  <% if @schedule.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@schedule.errors.count, "error") %> prohibited this schedule from being saved:</h2>
      <ul>
      <% @schedule.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
</div>
<div class="row">
  <div class="col-sm-6">
    <h3>Race info</h3>
    <div class="field">
      <%= f.label :name, "Schedule Name"%><br>
      <%= f.text_field :name, :placeholder => "required"  %>
    </div>
    <div class="field">
      <%= f.label :race_day %><br>
      <%= f.text_field :race_day, :id => "datepicker", :placeholder => "required"  %>
    </div>
    <div class="field">
      <%= f.label :race_type %><br>
      <%= f.select :race_type, RACE_TYPES %>
    </div>
  </div>
  <div class="col-sm-6">
    <h3>Weekly Activities</h3>
    <div class="field">
      <%= f.label :monday %><br>
      <%= f.select :monday, TRAINING_OPTIONS, :selected => "rest"  %>
    </div>
    <div class="field">
      <%= f.label :tuesday %><br>
      <%= f.select :tuesday, TRAINING_OPTIONS, :selected => "short run" %>
    </div>
    <div class="field">
      <%= f.label :wednesday %><br>
      <%= f.select :wednesday, TRAINING_OPTIONS, :selected => "medium run" %>
    </div>
    <div class="field">
      <%= f.label :thursday %><br>
      <%= f.select :thursday, TRAINING_OPTIONS, :selected => "cross train" %>
    </div>
    <div class="field">
      <%= f.label :friday %><br>
      <%= f.select :friday, TRAINING_OPTIONS, :selected => "short run"  %>
    </div>
    <div class="field">
      <%= f.label :saturday %><br>
      <%= f.select :saturday, TRAINING_OPTIONS, :selected =>  "rest" %>
    </div>
    <div class="field">
      <%= f.label :sunday %><br>
      <%= f.select :sunday, TRAINING_OPTIONS, :selected => "long run" %>
    </div>
    <div class="alert alert-info alert-dismissable">You can use the <a href=#training_table><b>table below</b></a> to figure out how many days of each activity you need to train for your race</div>
  </div>
    <div>
      <%= f.submit :class => "btn btn-primary btn-lg"%>
    </div>
  <% end %>
</div>

app/views/schedules/_training_table.html.erb
<h3>How many days for each activity?</td>
<table class="table table-striped">
  <tr>
    <td></td>
    <td><b>Full Marathon</b></td>
    <td><b>Half Marathon</b></td>
    <td><b>10K Race</b></td>
    <td><b>5k Race</b></td>
  </tr>
  <tr>
    <td><b>short run</b></td>
    <td>2 days</td>
    <td>2 days</td>
    <td>1 day</td>
    <td>1 day</td>
  </tr>
  <tr>
    <td><b>medium run</b></td>
    <td>1 day</td>
    <td>1 day</td>
    <td>1 day</td>
    <td>1 day</td>
  </tr>
  <tr>
    <td><b>long run</b></td>
    <td>1 day</td>
    <td>1 day</td>
    <td>1 day</td>
    <td>1 day</td>
  </tr>
  <tr>
    <td><b>rest</b></td>
    <td>2 days</td>
    <td>2 days</td>
    <td>3 days</td>
    <td>3 days</td>
  </tr>
  <tr>
    <td><b>cross train</b></td>
    <td>1 day</td>
    <td>1 day</td>
    <td>1 day</td>
    <td>1 day</td>
  </tr>
</table>

app/views/schedules/edit.html.erb
<h1>Editing Schedule</h1>

<div class="well create_well main_well col-md-6">
  <%= render 'form' %>
</div>

app/views/schedules/index.html.erb
<div class="well main_well">
  <h1><%= @user.username %>'s Schedules</h1>

  <table class = "table table-striped">
    <thead>
      <tr>
        <th>Schedule Name</th>
        <th>Race Date</th>
        <th>Race Type</th>
      </tr>
    </thead>

    <tbody>
      <% @schedules.each do |schedule| %>
        <tr>
          <td><b><%= link_to schedule.name, schedule %></b></td>
          <td><%= schedule.race_day.strftime('%m/%d/%y') %></td>
          <td><%= schedule.race_type %></td>
          <td>
            <div class="edit_button btn btn-primary">
              <%= link_to 'Edit', edit_schedule_path(schedule) %>
            </div>
            <div class="edit_button btn btn-danger">
              <%= link_to 'Delete', schedule, method: :delete, data: { confirm: 'Are you sure?' } %>
            </div>
          </td>
        </tr>
      <% end %>
    </tbody>
  </table>

  <br>

  <%= link_to 'New Schedule', new_schedule_path, :class => "btn btn-primary" %>
</div>

app/views/schedules/new.html.erb
<div class="row">
  <div class="form_container">
    <h1>New Schedule</h1>
    <div class="alert alert-info alert-dismissable">Fill out your race information and pick an training activity for each day of the week, then click "Create Schedule" to create your customized training plan!</div>
    <div class="well create_well main_well col-md-6">
      <%= render 'form' %>
    </div>
    <div id="training_table" class="well create_well main_well col-md-6">
      <%= render 'training_table' %>
    </div>
  </div>
</div>

app/views/schedules/show.html.erb
<div class="well main_well">
  <h1><%= @schedule.name %></h1>

  <div class="alert alert-info alert-dismissable">Click on an activity to mark it as completed and keep track
  of your progress!</div>

  <table class="table-bordered table-striped schedule-table">
    <tr>
      <td><b>Week</b></td>
      <td><b>Monday</b></td>
      <td><b>Tuesday</b></td>
      <td><b>Wednesday</b></td>
      <td><b>Thursday</b></td>
      <td><b>Friday</b></td>
      <td><b>Saturday</b></td>
      <td><b>Sunday</b></td>
    </tr>
    <% @schedule.weeks.order(:number).each do |week| %>
      <% if week.days.any? %>
        <tr>
          <td><b><p class="week_number"><%= week.number %><p></b></td>
          <% week.days.order(:date).each do |day| %>
              <%= render day, locals: { day: @day }%>
          <% end %>
        </tr>
      <% end %>
    <% end %>
  </table>
      
  <%= link_to 'Edit', edit_schedule_path(@schedule) %> 
</div>