config/routes.rb
Rails.application.routes.draw do
  resources :days
  resources :weeks
  resources :schedules
  root to: 'visitors#index'
  devise_for :users
  resources :users
  get 'days/:id/mark_completed', to: "days#mark_completed", as: 'mark_completed'
end

app/models/day.rb
class Day < ActiveRecord::Base
  belongs_to :weeks

  def toggle_completed
    self.update_attributes!({:completed => !self.completed})
  end
end

app/controllers/days_controller.rb
class DaysController < ApplicationController
  def mark_completed
    @day = Day.find(params[:id])
    @day.toggle_completed
    respond_to do |format|
      format.js
    end
  end
end

app/helpers/days_helper.rb
module DaysHelper
end

app/views/days/_day.html.erb
<% if day.completed? %>
  <td class="table_cell">
  <%= link_to mark_completed_path(day), remote: true, class: 'completed' do %>
    <%= div_for(day, class: "schedule_day") do %>
    <div class="completed_background">
      <p><em><%= day.date.strftime('%m/%d') %></em></p>
      <p class="activity"><b><%= day.activity %></b></p>
    </div>
    <% end %>
  <% end %>
  </td>
<% else%>
  <td class="table_cell">
  <%= link_to mark_completed_path(day), remote: true do %>
    <%= div_for day do %>
    <div class="normal_background">
      <p><em><%= day.date.strftime('%m/%d') %></em></p>
      <p class="activity"><b><%= day.activity %></b></p>
    <div class="normal_background">
    <% end %>
  <% end %>
  </td>
<% end %>

app/views/days/_form.html.erb
<%= form_for(@day, remote: true) do |f| %>
  <div class="field">
    <%= f.label :activity %><br>
    <%= f.text_field :date %>
  </div>
  <div class="field">
    <%= f.label :date %><br>
    <%= f.date_select :date %>
  </div>
  <div class="field">
    <%= f.label :completed %><br>
    <%= f.check_box :completed %>
  </div>
<% end %>

app/views/days/mark_completed.js.erb
$('#day_<%= @day.id %>').html("<%= escape_javascript(render partial: 'day', locals: { day: @day } ) %>"); 